### ISSUE TITLE
Document parse not valid

### ISSUE THREAD

**Issue by miguelramos** [appwrite/sdk-for-node#2]
Just trying this lib and it appears that data is not being fully parsed or docs are not correct.
for instance i tried a simple example as : 

```
const { Client, Database } = require('node-appwrite');

const sdk = new Client();
const db = new Database(sdk);

....

// uid=5d9630017f3ac
// let promise = db.createCollection('CHECK');
let promise = db.createDocument('5d9630017f3ac', JSON.stringify({ name: "Hello" }));

promise.then(
  function(response) {
    console.log(response);
  },
  function(error) {
    console.log(error);
  }
);
```

And console show error on promise:

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/495720/66150886-105d6e80-e60e-11e9-8fc3-1ebc4b54f2af.png">

Docs tell to use as:

<img width="620" alt="image" src="https://user-images.githubusercontent.com/495720/66150933-28cd8900-e60e-11e9-9695-a7566c50af31.png">

Perhaps schema validation when passing data? Just a thought... What could be wrong in this example?

Regards, and thanks for the hard work :)

**Comment by eldadfux** [comment]
This error is a bug in the server not able to parse your string to a JSON object. I have already committed a fix for next version.
https://github.com/appwrite/appwrite/commit/f0f3211ef056839c932b2e8d32c8be8c9e30f3a3

For now you can bypass this bug by passing an object instead of a string.

Notice that after you will fix that issue your sample code will still fail because your collection has no structure defined. This is a part that is not well documented and we are working to fix it.

For now you can follow this example when creating a new collection:

```js
const { Client, Database } = require('node-appwrite');

const sdk = new Client();
const db = new Database(sdk);

sdk
    .setProject('5d8fa6deefd05')
    .setEndpoint('http://localhost/v1')
    .setKey('1589eb89e0c0153892...')
    ;

let promise = db.createCollection('movies',
    ['*'], // public read access
    ['user:[MY_USER_ID]'], // write access only to a specific user
    [
        {
            "label": "Name",
            "key": "name",
            "type": "text",
            "default": "",
            "required": true,
            "array": false
        },
        {
            "label": "Release Year",
            "key": "releaseYear",
            "type": "numeric",
            "default": 0,
            "required": false,
            "array": false
        },
    ]
);

promise.then(
  function(response) {
    console.log(response);
  },
  function(error) {
    console.log(error);
  }
);
````

Currently the Database API rules support this types of data validations for your collection document structure:
* text (any string)
* numeric (integer, or float)
* email (valid email address)
* ip (valid ip address)
* boolean (true or false value)
* uid (Appwrite UID format)

There is also an option to nest one document into another and limit text length and number ranges. I am working on a tutorial to explain this features in more detail.

**Comment by miguelramos** [comment]
@eldadfux thanks. I saw the parameters here:

<img width="709" alt="image" src="https://user-images.githubusercontent.com/495720/66165476-b4561280-e62c-11e9-97a0-8d6f79fd5592.png">

And thought they were optional and described in the docs, but looks like that the rules should be mandatory. If not they will create confusion.

**Comment by miguelramos** [comment]
Found here the rules docs: https://appwrite.io/docs/rules
